# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='theme',
            field=models.ManyToManyField(related_name='themes', to='metrics.Theme'),
        ),
    ]
